from . import binding


from . import account_invoice
from . import account_payment_mode
from . import account_tax
from . import account_tax_group
from . import res_partner
from . import prestashop_backend
from . import res_partner_category
from . import res_lang
from . import binding
from . import sale_order
from . import sale_order_state
from . import prestashop_shop_group
from . import stock_move
from . import stock_warehouse
from . import delivery_carrier
from . import product_category
from . import product_image
from . import product_pricelist
from . import product_template
from . import product_product
from . import product_supplierinfo
from . import res_country
from . import res_country_state
from . import res_currency
from . import queue_job
from . import mail_message
